### PR TITLE
Fix partition suffix bug

### LINKED ISSUE #347: Asherah java client doesn't properly compute Intermediate DynamoDB Keys (with expected suffixes)
**Describe the bug**

Asherah java client doesn't properly compute Intermediate DynamoDB Keys (with expected suffixes)

**To Reproduce**

A Simplified Kotlin/Spring class to process incoming data:
```
@Service
class DecryptionService {
    val messageConverter = MappingJackson2MessageConverter()

    @Value("\${cloud.aws.resources.dynamodb.messageEncryptionTableNames.analyticEvent}")
    lateinit var tableName: String

    @Value("\${cloud.aws.resources.kms.messageEncryptionKeysArn.analyticEvent}")
    lateinit var kmsKeyArn: String

    @Value("\${cloud.aws.region.static}")
    lateinit var awsRegion: String

    @Value("\${serviceName}")
    lateinit var serviceName: String

    @Value("\${sqsEncryptionService.keyExpirationDays}")
    var keyExpirationDays: Int = 0

    @Value("\${sqsEncryptionService.revokeCheckMinutes}")
    var revokeCheckMinutes: Int = 0

    lateinit var sessionFactory: SessionFactory

    @PostConstruct
    fun init() {
        val metastore = DynamoDbMetastoreImpl
            .newBuilder(awsRegion) // .com.godaddy.asherah:appencryption:0.1.4
            .withKeySuffix() // doesn't work with suffixes
            .withRegion(awsRegion)
            .withTableName(tableName)
            .build()

        val cryptoPolicy = BasicExpiringCryptoPolicy
            .newBuilder()
            .withKeyExpirationDays(keyExpirationDays)
            .withRevokeCheckMinutes(revokeCheckMinutes)
            .build()

        val regionMap = mapOf(awsRegion to kmsKeyArn)
        val kms = AwsKeyManagementServiceImpl
            .newBuilder(regionMap, awsRegion)
            .build()

        val productId = "${serviceName}-analytic-event"
        val serviceId = "over"
        sessionFactory = SessionFactory
            .newBuilder(productId, serviceId) // ("segment-api", "over")
            .withMetastore(metastore)
            .withCryptoPolicy(cryptoPolicy)
            .withKeyManagementService(kms)
            .build()

        logger.info("Decryption service has been initialized (tableName: ${tableName}, region: ${awsRegion}, kmsKeyArn: ${kmsKeyArn}, productId: ${productId}, serviceId: ${serviceName})")
    }

    fun decrypt(id: String, payload: String): ByteArray {
        val sessionBytes = sessionFactory.getSessionBytes(id)
        return sessionBytes.decrypt(payload.toByteArray())
    }

    companion object {
        private val logger = LoggerFactory.getLogger(SqsQueueController::class.java.name)
    }
}
```

A simplified GoLang class to encrypt/send messages:
```
type Encryptor struct {
	sessionFactory *appencryption.SessionFactory
	metastore      *persistence.DynamoDBMetastore
	base64Encoder  *base64.Encoding
}

func New(input *NewInput) (*Encryptor, error) {
	serviceName, tableName, keyArn, sess := input.ServiceName, input.TableName, input.KMSKeyARN, input.Session

	crypto := aead.NewAES256GCM()

	config := &appencryption.Config{
		Service: "over",
		Product: serviceName,
		Policy:  appencryption.NewCryptoPolicy(),
	}

	metastore := persistence.NewDynamoDBMetastore(
		input.Session,
		persistence.WithDynamoDBRegionSuffix(true),
		persistence.WithTableName(tableName),
	)

	region := aws.StringValue(sess.Config.Region)
	regionArnMap := map[string]string{
		region: keyArn,
	}

	key, err := kms.NewAWS(crypto, region, regionArnMap)
	if err != nil {
		return nil, fmt.Errorf("unable to init kms key: %w", err)
	}

	sessionFactory := appencryption.NewSessionFactory(config, metastore, key, crypto)

	return &Encryptor{
		sessionFactory: sessionFactory,
		metastore:      metastore,
		base64Encoder:  base64.StdEncoding,
	}, nil
}

func (e *Encryptor) Encrypt(ctx context.Context, key string, payload string) (string, error) {
	sess, err := e.sessionFactory.GetSession(key)
	if err != nil {
		return "", fmt.Errorf("unable to init session: %w", err)
	}

	res, err := sess.Encrypt(ctx, []byte(payload))
	if err != nil {
		return "", fmt.Errorf("unable to encrypt the message: %w", err)
	}

	resBytes, err := json.Marshal(res)
	if err != nil {
		return "", fmt.Errorf("unable to marshal encrypted record: %w", err)
	}

	return string(resBytes), nil
}
```

Set up a transport around those classes, and send some payload.

What we found is that the version **higher than 0.1.1** (even with the `.withKeySuffix()` setting on) computes the IK names wrongly (without suffixes) ending up with the error:
```
com.godaddy.asherah.appencryption.exceptions.MetadataMissingException: Could not find EnvelopeKeyRecord with keyId=**_IK_21ff0288-89e8-5885-b157-5a49938aa3ef_over_segment-api-analytic-event**, created=2021-03-09T06:39:00Z
	at com.godaddy.asherah.appencryption.envelope.EnvelopeEncryptionJsonImpl.lambda$loadKeyRecord$14(EnvelopeEncryptionJsonImpl.java:461)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.godaddy.asherah.appencryption.envelope.EnvelopeEncryptionJsonImpl.loadKeyRecord(EnvelopeEncryptionJsonImpl.java:460)
	at com.godaddy.asherah.appencryption.envelope.EnvelopeEncryptionJsonImpl.getIntermediateKey(EnvelopeEncryptionJsonImpl.java:411)
	at com.godaddy.asherah.appencryption.envelope.EnvelopeEncryptionJsonImpl.withIntermediateKeyForRead(EnvelopeEncryptionJsonImpl.java:134)
	at com.godaddy.asherah.appencryption.envelope.EnvelopeEncryptionJsonImpl.lambda$decryptDataRowRecord$2(EnvelopeEncryptionJsonImpl.java:80)
	at io.micrometer.core.instrument.noop.NoopTimer.record(NoopTimer.java:36)
```

Whereas the IK has been created by go client of the view: _IK_21ff0288-89e8-5885-b157-5a49938aa3ef_over_segment-api-analytic-event_us-west-2

image

### PR DESCRIPTION
**Pull request by aka-bo**
This is essentially a revert of #253.

Resolves #347

### CODE REVIEW

File: java/app-encryption/src/it/java/com/godaddy/asherah/regression/DynamoDbGlobalTableIT.java [hunk 1]
```diff
@@ -71,24 +71,46 @@ void testRegionSuffixBackwardCompatibility() {
     byte[] decryptedBytes;
```
Comment (sushantmimani) [inline java/app-encryption/src/it/java/com/godaddy/asherah/regression/DynamoDbGlobalTableIT.java:71]: We should probably add another test where we encrypt with suffix and decrypt without suffix.

**Review by sushantmimani — APPROVED** [review]
Looks good.
